debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.grow.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.spi: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: ssang
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always